#!/usr/bin/env bash
# 93-ticketflow.sh — install Jira-triggered intake for remote Claude sessions.
# Sourced by setup.sh; defines module_main.

TICKETFLOW_CONFIG_DIR="${TICKETFLOW_CONFIG_DIR:-${HOME}/.config/ticketflow}"
TICKETFLOW_STATE_DIR="${TICKETFLOW_STATE_DIR:-${HOME}/.local/state/ticketflow}"
TICKETFLOW_DEST="${TICKETFLOW_DEST:-${HOME}/.local/bin/ticketflow}"
TICKETFLOW_PLIST="${TICKETFLOW_PLIST:-${HOME}/Library/LaunchAgents/ai.chatbooks.ticketflow.plist}"
TICKETFLOW_JIRA_READY=0

module_main() {
  export PATH="${HOME}/.local/bin:/opt/homebrew/bin:${PATH}"

  have python3 || { log_error "python3 missing"; return 1; }
  [[ -x "${HOME}/spawn-session.sh" ]] || { log_error "missing ${HOME}/spawn-session.sh"; return 1; }

  _ticketflow_install_cli || return 1
  _ticketflow_write_env
  _ticketflow_install_launch_agent || return 1
  _ticketflow_report
  return 0
}

_ticketflow_install_cli() {
  local src="${REPO_ROOT}/bin/ticketflow"
  [[ -f "${src}" ]] || { log_error "missing ${src}"; return 1; }
  mkdir -p "${TICKETFLOW_STATE_DIR}/pycache"
  PYTHONPYCACHEPREFIX="${TICKETFLOW_STATE_DIR}/pycache" \
    python3 -m py_compile "${src}" || { log_error "${src} has a syntax error"; return 1; }
  mkdir -p "$(dirname "${TICKETFLOW_DEST}")"
  install -m 0755 "${src}" "${TICKETFLOW_DEST}"
  log_ok "installed Ticketflow at ${TICKETFLOW_DEST}"
}

_ticketflow_write_env() {
  local jira_email jira_token
  local env_file="${TICKETFLOW_CONFIG_DIR}/env"
  if [[ -f "${env_file}" ]]; then
    # This file is generated by this module and mode 0600. Preserve configured
    # credentials across idempotent setup reruns.
    # shellcheck disable=SC1090
    source "${env_file}"
  fi
  jira_email="$(get_secret JIRA_EMAIL "MacSetup/jira-email/username" "Jira account email for Ticketflow" --optional)"
  jira_token="$(get_secret JIRA_API_TOKEN "MacSetup/jira-api-token" "Jira API token for Ticketflow" --optional)"

  mkdir -p "${TICKETFLOW_CONFIG_DIR}"
  local tmp="${env_file}.tmp.$$"
  : >"${tmp}"
  chmod 600 "${tmp}"
  {
    printf 'JIRA_BASE_URL=%q\n' "${JIRA_BASE_URL:-https://chatbookstown.atlassian.net}"
    printf 'JIRA_EMAIL=%q\n' "${jira_email}"
    printf 'JIRA_API_TOKEN=%q\n' "${jira_token}"
    printf 'TICKETFLOW_WORKSPACE=%q\n' "${WORKSPACE_DIR:-${HOME}/workspace}"
  } >>"${tmp}"
  mv "${tmp}" "${env_file}"
  chmod 600 "${env_file}"

  if [[ -n "${jira_email}" && -n "${jira_token}" ]]; then
    TICKETFLOW_JIRA_READY=1
    log_ok "wrote Ticketflow Jira credentials to ${env_file} (mode 600)"
  else
    log_warn "Ticketflow Jira credentials are incomplete; manual starts work, polling will not"
    add_manual_todo "Set JIRA_EMAIL and JIRA_API_TOKEN in ${env_file}, then run: ticketflow doctor"
  fi
}

_ticketflow_install_launch_agent() {
  local template="${REPO_ROOT}/templates/launchagents/ai.chatbooks.ticketflow.plist.tmpl"
  [[ -f "${template}" ]] || { log_error "missing ${template}"; return 1; }
  mkdir -p "$(dirname "${TICKETFLOW_PLIST}")" "${TICKETFLOW_STATE_DIR}/logs"
  sed "s|\${HOME}|${HOME}|g" "${template}" >"${TICKETFLOW_PLIST}"
  plutil -lint "${TICKETFLOW_PLIST}" >/dev/null || {
    log_error "invalid launchd plist: ${TICKETFLOW_PLIST}"
    return 1
  }

  local domain
  domain="gui/$(id -u)"
  launchctl bootout "${domain}/ai.chatbooks.ticketflow" >/dev/null 2>&1 || true
  if [[ "${TICKETFLOW_JIRA_READY}" != "1" ]]; then
    log_warn "Ticketflow launch agent installed but not loaded until Jira credentials are configured"
    add_manual_todo "After configuring Jira, rerun: MACSETUP_FORCE=1 ./setup.sh --only 93-ticketflow"
    return 0
  fi
  if launchctl bootstrap "${domain}" "${TICKETFLOW_PLIST}" >>"${LOG_FILE}" 2>&1; then
    launchctl kickstart -k "${domain}/ai.chatbooks.ticketflow" >>"${LOG_FILE}" 2>&1 || true
    log_ok "Ticketflow launch agent loaded (60-second Jira poll)"
  else
    log_warn "could not load Ticketflow launch agent"
    add_manual_todo "Load Ticketflow: launchctl bootstrap ${domain} ${TICKETFLOW_PLIST}"
  fi
}

_ticketflow_report() {
  if "${TICKETFLOW_DEST}" doctor >>"${LOG_FILE}" 2>&1; then
    log_ok "ticketflow doctor passed"
  else
    log_warn "ticketflow doctor has incomplete prerequisites — see ${LOG_FILE}"
  fi
  log_info "manual usage: ticketflow start https://chatbookstown.atlassian.net/browse/MEMS-123"
}
